[tool.poetry]
name = "prometheus-kubernetes-cli"
version = "0.1.0"
description = ""
authors = ["avi@robusta.dev <avi@robusta.dev>"]
readme = "README.md"
packages = [{include = "prometheus_kubernetes_cli"}]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.28.15"
botocore = "^1.31.15"
prometheus-api-client = "0.5.3"
requests = "^2.31.0"
pydantic = "1.10.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
